### ISSUE TITLE
Doesn't recognize card number well

### ISSUE THREAD

**Issue by JaDenis** [narlei/CardScanner#1]
Hi, great work, first of all!
The library doesn't really do it's job, it doesn't recognize numbers well (tried it with different lightings)
Do we need a separate OCR engine to make it detect digits with no error?

**Comment by narlei** [comment]
Hello!
I updated the code to recognise cards with 15 digits too, now are working with 15 and 16 digits.
If still not working, please take a photo from your card, and remove the date, name and cvv, keeping only the number, and attach here, I can debug what are doing with the model of your card.
